Feat/prt 1768 - get editor content
iarahealth/adapters pull request #14
Opened 2023-09-26 21:03 UTC by dehcanuto

get editor content

2023-09-28 19:06 UTC, dsouza95 requested changes

2023-09-28 19:06 UTC, dsouza95 commented on src/syncfusion/index.ts
> +  private get _recognitionInternal(): any {
Aparentemente este getter não é utilizado, pode ser removido por enquanto ao menos.

2023-09-28 19:06 UTC, dsouza95 commented on src/syncfusion/index.ts
> +    const content = await this._editor.saveAsBlob("Sfdt")
Na tarefa, foi especificado que este método deveria retornar o conteúdo em HTML. Isso está certo?

2023-10-02 12:22 UTC, dsouza95 requested changes

2023-10-02 12:22 UTC, dsouza95 commented on src/syncfusion/index.ts
> +    const content = await this._editor.saveAsBlob("Txt")
Ainda não é Html, era pra ser outro formato mesmo? Se não, use saveAsBlob("Html")

2023-10-03 11:45 UTC, dehcanuto commented on src/syncfusion/index.ts
> +    const content = await this._editor.saveAsBlob("Txt")
O editor consegue exportar apenas pra tres formatos: docx, txt ou sfdt. Irei fazer uma solucao usando o conversor do sfdt para html.

Documentacao: Document Editor exports the document into various known file formats in client-side such as Microsoft Word document (.docx), text document (.txt), and its own format called Syncfusion Document Text (.sfdt).

2023-10-03 13:01 UTC, dsouza95 requested changes

2023-10-03 13:01 UTC, dsouza95 commented on src/syncfusion/index.ts
> +    const content = await this._editor.saveAsBlob("Txt")
Faz sentido. Ainda assim, eu testaria o saveAsBlob("Html") só por via das dúvidas. Na referência da API, teoricamente deveria ser possível: https://ej2.syncfusion.com/documentation/api/document-editor/#saveasblob
Mas creio que seja apenas um erro na referência da API.

2023-10-03 18:53 UTC, dsouza95 approved these changes

2023-10-04 12:01 UTC, closed without merging