feature PRT-1743 done
iarahealth/adapters pull request #6
Opened 2023-08-07 11:50 UTC by dehcanuto

2023-08-24 12:54 UTC, dsouza95 requested changes

2023-08-24 12:54 UTC, dsouza95 commented on src/syncfusion/index.ts
> +    const lastContent = this._editorContent.end.paragraph.lastChild as any
Verificar se é possível utilizar esta API: https://ej2.syncfusion.com/documentation/document-editor/how-to/get-current-word

2023-09-04 17:33 UTC, dehcanuto commented on src/syncfusion/index.ts
> +    this._editorAPI.insertText(text)
feito

2023-09-04 17:33 UTC, dehcanuto commented on src/syncfusion/index.ts
> +    // caso nao saia nada da gravação, parar propagação.
feito

2023-09-04 17:33 UTC, dehcanuto commented on src/syncfusion/index.ts
> +  private get _editorContent(): Selection {
feito

2023-09-04 17:34 UTC, dehcanuto commented on src/syncfusion/index.ts
> +    // Precisou ser "any" por falta de declarações corretas no "@syncfusion/ej2-documenteditor"
feito

2023-09-04 17:34 UTC, dehcanuto commented on src/syncfusion/index.ts
> +    const lastContent = this._editorContent.end.paragraph.lastChild as any
feito

2023-09-04 18:03 UTC, dsouza95 requested changes

2023-09-26 16:40 UTC, closed without merging